version: '3'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@travelexpense
      MYSQL_DATABASE: travelexpense
    command: --init-file /mysql/scripts/init.sql
    volumes:
      - ./mysql:/mysql
    ports:
      - "3030:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 15
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
