version: '3'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@travelexpense
      MYSQL_DATABASE: travelexpense
    command: --init-file /mysql/scripts/init.sql
    volumes:
      - ./mysql:/mysql
    ports:
      - "3333:3306"
volumes:
  db_data:
